spring.application.name=micuenta
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mi_cuenta}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:isabella2007}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${JWT_SECRET:bXktc3VwZXItc2VjdXJlLWp3dC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHktY2hhbmdlLW1lLW5vdy0xMjM0NTY3ODkw}
security.jwt.expiration-minutes=120


gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
gemini.api-base-url=${GEMINI_API_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
